export enum Constants {
  LOGIN = "Login",
  CUSTOMER = "Customer",
  CUSTOMER_LIST = "Customer List",
  ADMIN_LIST = "Admin List",
  ADMIN = "Admin",
  PIZZA = "Pizza",
  PIZZA_LIST = "Pizza List",
  ADD_PIZZA = "Add Pizza",
  UPDATE_PIZZA = "Update Pizza",
  UPDATE_PROFILE = "Update Profile",
  ORDER = "Order",
  MY_ORDERS = "My Orders",
  ORDER_LIST = "Order List",
  MY_PROFILE = "My Profile",
  ADD_TO_CART = "Add to Cart",
  CART = "Cart",
  CHECKOUT = "Checkout",
  ORDER_HISTORY = "Order History",
  ORDER_DETAILS = "Order Details",
  SIGN_UP = "Sign Up",
  LOGOUT = "Logout",
  HOME = "Home",
  ABOUT = "About",
  CONTACT = "Contact",
  TOKEN = "Token",
}
